CREATE DATABASE IF NOT EXISTS `auth` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `characters` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS `world` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE USER IF NOT EXISTS 'trinity'@'%' IDENTIFIED BY 'trinity';

GRANT ALL PRIVILEGES ON `auth`.* TO 'trinity'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `characters`.* TO 'trinity'@'%' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON `world`.* TO 'trinity'@'%' WITH GRANT OPTION;

FLUSH PRIVILEGES;
